main: com.blalp.chatdirector.ChatDirectorBukkit
version: 0.1.8
name: ChatDirector
softdepend: [Vault, LuckPerms]
load: POSTWORLD
author: blalp
permissions:
  chatdirector.reload:
    description: "Allows reloading of chatdirector"
commands:
  chatdirectorlocal:
    permission: chatdirector.reload
    description: "Allows reloading of chatdirector"
