main: com.blalp.chatdirector.ChatDirectorBungee
version: 0.1.2-beta
name: ChatDirector
softdepend: [Vault,LuckPerms]
load: POSTWORLD
author: blalp
permissions:
  chatdirector.reload:
    description: "Allows reloading of chatdirector"
commands:
  chatdirector:
    permission: chatdirector.reload
    description: "Allows reloading of chatdirector"
